-- ============================================================
-- SP_INS_WEEK_ALERT_POPUP: 관리대상 모돈 추출 프로시저 (통합 버전)
--
-- 상세 문서: docs/db/ins/week/12.alert-popup.md
--
-- 최적화:
--   - 5개 개별 쿼리 → 단일 WITH절 통합 쿼리로 변경
--   - 20개 변수 → INSERT SELECT로 직접 INSERT
--   - LAST_WK CTE를 공통으로 1회만 실행
-- ============================================================

CREATE OR REPLACE PROCEDURE SP_INS_WEEK_ALERT_POPUP (
    P_MASTER_SEQ    IN  NUMBER,
    P_JOB_NM        IN  VARCHAR2,
    P_FARM_NO       IN  INTEGER,
    P_LOCALE        IN  VARCHAR2,
    P_DT_FROM       IN  VARCHAR2,
    P_DT_TO         IN  VARCHAR2
) AS
    V_LOG_SEQ       NUMBER;
    V_PROC_CNT      INTEGER := 0;
    V_BASE_DT       DATE := TO_DATE(P_DT_TO, 'YYYYMMDD');

    -- 농장 설정값
    V_FIRST_GB_DAY  NUMBER := 240;  -- 후보돈초교배일령 (140007)
    V_AVG_RETURN    NUMBER := 7;    -- 평균재귀일 (140008)
    V_PREG_PERIOD   NUMBER := 115;  -- 평균임신기간 (140002)
    V_WEAN_PERIOD   NUMBER := 21;   -- 평균포유기간 (140003)

BEGIN
    SP_INS_COM_LOG_START(P_MASTER_SEQ, P_JOB_NM, 'SP_INS_WEEK_ALERT_POPUP', P_FARM_NO, V_LOG_SEQ);

    -- 농장 설정값 조회
    BEGIN
        SELECT NVL(MAX(CASE WHEN CODE = '140007' THEN TO_NUMBER(CVALUE) END), 240),
               NVL(MAX(CASE WHEN CODE = '140008' THEN TO_NUMBER(CVALUE) END), 7),
               NVL(MAX(CASE WHEN CODE = '140002' THEN TO_NUMBER(CVALUE) END), 115),
               NVL(MAX(CASE WHEN CODE = '140003' THEN TO_NUMBER(CVALUE) END), 21)
        INTO V_FIRST_GB_DAY, V_AVG_RETURN, V_PREG_PERIOD, V_WEAN_PERIOD
        FROM TC_FARM_CONFIG
        WHERE FARM_NO = P_FARM_NO AND CODE IN ('140007', '140008', '140002', '140003');
    EXCEPTION WHEN NO_DATA_FOUND THEN NULL;
    END;

    -- 기존 데이터 삭제 (재실행 대비)
    DELETE FROM TS_INS_WEEK_SUB
    WHERE MASTER_SEQ = P_MASTER_SEQ AND FARM_NO = P_FARM_NO AND GUBUN = 'ALERT';

    -- ================================================
    -- 통합 쿼리: 5개 유형 × 4개 구간을 한 번에 집계 후 INSERT
    -- ================================================
    INSERT INTO TS_INS_WEEK_SUB (
        MASTER_SEQ, FARM_NO, GUBUN, SORT_NO, CODE_1,
        CNT_1, CNT_2, CNT_3, CNT_4, CNT_5
    )
    WITH
    -- 공통: 최종 작업 SEQ (1회만 조회)
    LAST_WK AS (
        SELECT FARM_NO, PIG_NO, MAX(SEQ) AS MSEQ
        FROM TB_MODON_WK
        WHERE FARM_NO = P_FARM_NO AND USE_YN = 'Y'
        GROUP BY FARM_NO, PIG_NO
    ),
    -- 1) 미교배 후보돈
    --    조건1: STATUS_CD='010001' (후보돈) AND 작업이력 없음
    --    조건2: STATUS_CD='010002' (임신돈) AND IN_SANCHA=0 AND IN_GYOBAE_CNT=1 AND 작업이력 없음
    HUBO AS (
        SELECT (V_BASE_DT - MD.BIRTH_DT) - V_FIRST_GB_DAY AS DELAY_DAYS
        FROM TB_MODON MD
        WHERE MD.FARM_NO = P_FARM_NO
          AND MD.OUT_DT = TO_DATE('9999-12-31', 'YYYY-MM-DD')
          AND MD.USE_YN = 'Y'
          AND MD.IN_DT < V_BASE_DT + 1
          AND (V_BASE_DT - MD.BIRTH_DT) - V_FIRST_GB_DAY >= 0
          AND (
              MD.STATUS_CD = '010001'  -- 후보돈
              OR (MD.STATUS_CD = '010002' AND MD.IN_SANCHA = 0 AND MD.IN_GYOBAE_CNT = 1)  -- 전입 임신돈 (초교배)
          )
          AND NOT EXISTS (SELECT 1 FROM TB_MODON_WK WK WHERE WK.FARM_NO = P_FARM_NO AND WK.PIG_NO = MD.PIG_NO AND WK.USE_YN = 'Y')
    ),
    -- 2) 이유후 미교배 (작업이력 + 전입돈)
    EU_MI AS (
        SELECT (V_BASE_DT - TO_DATE(WK.WK_DT, 'YYYYMMDD')) - V_AVG_RETURN + 1 AS DELAY_DAYS
        FROM TB_MODON MD
        JOIN LAST_WK LW ON LW.FARM_NO = MD.FARM_NO AND LW.PIG_NO = MD.PIG_NO
        JOIN TB_MODON_WK WK ON WK.FARM_NO = LW.FARM_NO AND WK.PIG_NO = LW.PIG_NO AND WK.SEQ = LW.MSEQ
        WHERE MD.FARM_NO = P_FARM_NO
          AND MD.OUT_DT = TO_DATE('9999-12-31', 'YYYY-MM-DD') AND MD.USE_YN = 'Y'
          AND WK.WK_GUBUN = 'E' AND WK.DAERI_YN = 'N'
          AND (V_BASE_DT - TO_DATE(WK.WK_DT, 'YYYYMMDD')) + 1 >= V_AVG_RETURN
        UNION ALL
        SELECT (V_BASE_DT - MD.LAST_WK_DT) - V_AVG_RETURN AS DELAY_DAYS
        FROM TB_MODON MD
        WHERE MD.FARM_NO = P_FARM_NO AND MD.STATUS_CD = '010005'
          AND MD.OUT_DT = TO_DATE('9999-12-31', 'YYYY-MM-DD') AND MD.USE_YN = 'Y'
          AND MD.IN_DT < V_BASE_DT + 1
          AND (V_BASE_DT - MD.LAST_WK_DT) - V_AVG_RETURN >= 0
          AND NOT EXISTS (SELECT 1 FROM TB_MODON_WK WK WHERE WK.FARM_NO = P_FARM_NO AND WK.PIG_NO = MD.PIG_NO AND WK.USE_YN = 'Y')
    ),
    -- 3) 사고후 미교배 (작업이력 + 전입돈)
    SG_MI AS (
        SELECT (V_BASE_DT - TO_DATE(WK.WK_DT, 'YYYYMMDD')) AS DELAY_DAYS
        FROM TB_MODON MD
        JOIN LAST_WK LW ON LW.FARM_NO = MD.FARM_NO AND LW.PIG_NO = MD.PIG_NO
        JOIN TB_MODON_WK WK ON WK.FARM_NO = LW.FARM_NO AND WK.PIG_NO = LW.PIG_NO AND WK.SEQ = LW.MSEQ
        WHERE MD.FARM_NO = P_FARM_NO
          AND MD.OUT_DT = TO_DATE('9999-12-31', 'YYYY-MM-DD') AND MD.USE_YN = 'Y'
          AND WK.WK_GUBUN = 'F'
          AND (V_BASE_DT - TO_DATE(WK.WK_DT, 'YYYYMMDD')) >= 0
        UNION ALL
        SELECT (V_BASE_DT - MD.LAST_WK_DT) AS DELAY_DAYS
        FROM TB_MODON MD
        WHERE MD.FARM_NO = P_FARM_NO AND MD.STATUS_CD IN ('010006', '010007')
          AND MD.OUT_DT = TO_DATE('9999-12-31', 'YYYY-MM-DD') AND MD.USE_YN = 'Y'
          AND MD.IN_DT < V_BASE_DT + 1
          AND (V_BASE_DT - MD.LAST_WK_DT) >= 0
          AND NOT EXISTS (SELECT 1 FROM TB_MODON_WK WK WHERE WK.FARM_NO = P_FARM_NO AND WK.PIG_NO = MD.PIG_NO AND WK.USE_YN = 'Y')
    ),
    -- 4) 분만지연 (최종 교배)
    BM_DELAY AS (
        SELECT (V_BASE_DT - TO_DATE(WK.WK_DT, 'YYYYMMDD')) - V_PREG_PERIOD AS DELAY_DAYS
        FROM TB_MODON MD
        JOIN LAST_WK LW ON LW.FARM_NO = MD.FARM_NO AND LW.PIG_NO = MD.PIG_NO
        JOIN TB_MODON_WK WK ON WK.FARM_NO = LW.FARM_NO AND WK.PIG_NO = LW.PIG_NO AND WK.SEQ = LW.MSEQ
        WHERE MD.FARM_NO = P_FARM_NO
          AND MD.OUT_DT = TO_DATE('9999-12-31', 'YYYY-MM-DD') AND MD.USE_YN = 'Y'
          AND WK.WK_GUBUN = 'G'
          AND (V_BASE_DT - TO_DATE(WK.WK_DT, 'YYYYMMDD')) - V_PREG_PERIOD >= 0
    ),
    -- 5) 이유지연 (최종 분만)
    EU_DELAY AS (
        SELECT (V_BASE_DT - TO_DATE(WK.WK_DT, 'YYYYMMDD')) - V_WEAN_PERIOD AS DELAY_DAYS
        FROM TB_MODON MD
        JOIN LAST_WK LW ON LW.FARM_NO = MD.FARM_NO AND LW.PIG_NO = MD.PIG_NO
        JOIN TB_MODON_WK WK ON WK.FARM_NO = LW.FARM_NO AND WK.PIG_NO = LW.PIG_NO AND WK.SEQ = LW.MSEQ
        WHERE MD.FARM_NO = P_FARM_NO
          AND MD.OUT_DT = TO_DATE('9999-12-31', 'YYYY-MM-DD') AND MD.USE_YN = 'Y'
          AND WK.WK_GUBUN = 'B'
          AND (V_BASE_DT - TO_DATE(WK.WK_DT, 'YYYYMMDD')) - V_WEAN_PERIOD >= 0
    ),
    -- 구간 정의
    PERIODS AS (
        SELECT 1 AS SORT_NO, '~3'   AS PERIOD, 0 AS MIN_DAY, 3    AS MAX_DAY FROM DUAL UNION ALL
        SELECT 2, '4~7',  4, 7    FROM DUAL UNION ALL
        SELECT 3, '8~14', 8, 14   FROM DUAL UNION ALL
        SELECT 4, '14~',  15, 9999 FROM DUAL
    )
    -- 최종 집계
    SELECT
        P_MASTER_SEQ, P_FARM_NO, 'ALERT', P.SORT_NO, P.PERIOD,
        NVL((SELECT COUNT(*) FROM HUBO     WHERE DELAY_DAYS >= P.MIN_DAY AND DELAY_DAYS <= P.MAX_DAY), 0),
        NVL((SELECT COUNT(*) FROM EU_MI    WHERE DELAY_DAYS >= P.MIN_DAY AND DELAY_DAYS <= P.MAX_DAY), 0),
        NVL((SELECT COUNT(*) FROM SG_MI    WHERE DELAY_DAYS >= P.MIN_DAY AND DELAY_DAYS <= P.MAX_DAY), 0),
        NVL((SELECT COUNT(*) FROM BM_DELAY WHERE DELAY_DAYS >= P.MIN_DAY AND DELAY_DAYS <= P.MAX_DAY), 0),
        NVL((SELECT COUNT(*) FROM EU_DELAY WHERE DELAY_DAYS >= P.MIN_DAY AND DELAY_DAYS <= P.MAX_DAY), 0)
    FROM PERIODS P
    ORDER BY P.SORT_NO;

    V_PROC_CNT := SQL%ROWCOUNT;

    -- TS_INS_WEEK 요약 업데이트 (서브쿼리로 합계 계산)
    UPDATE TS_INS_WEEK W
    SET (ALERT_TOTAL, ALERT_HUBO, ALERT_EU_MI, ALERT_SG_MI, ALERT_BM_DELAY, ALERT_EU_DELAY) = (
        SELECT NVL(SUM(CNT_1 + CNT_2 + CNT_3 + CNT_4 + CNT_5), 0),
               NVL(SUM(CNT_1), 0), NVL(SUM(CNT_2), 0), NVL(SUM(CNT_3), 0),
               NVL(SUM(CNT_4), 0), NVL(SUM(CNT_5), 0)
        FROM TS_INS_WEEK_SUB S
        WHERE S.MASTER_SEQ = P_MASTER_SEQ AND S.FARM_NO = P_FARM_NO AND S.GUBUN = 'ALERT'
    )
    WHERE W.MASTER_SEQ = P_MASTER_SEQ AND W.FARM_NO = P_FARM_NO;

    COMMIT;
    SP_INS_COM_LOG_END(V_LOG_SEQ, V_PROC_CNT);

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        SP_INS_COM_LOG_ERROR(V_LOG_SEQ, SQLCODE, SQLERRM);
        RAISE;
END SP_INS_WEEK_ALERT_POPUP;
/

-- 프로시저 확인
SELECT OBJECT_NAME, STATUS FROM USER_OBJECTS WHERE OBJECT_NAME = 'SP_INS_WEEK_ALERT_POPUP';
